class diff_match_patch:
    DIFF_EQUAL: int
    DIFF_INSERT: int
    DIFF_DELETE: int

    def __init__(self) -> None: ...
    def diff_main(self, text1: str, text2: str, checklines: bool = ..., deadline: float | None = ...) -> list[tuple[int, str]]: ...
    def diff_cleanupSemantic(self, diffs: list[tuple[int, str]]) -> None: ...